id: I4CEE4109
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:49:28+00:00'
last_modified: '2022-06-08T05:01:09.563451+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29701
  title: གསུང་འབུམ། ཚེ་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A1DD:
      image_group_id: I5618
      title: ''
      total_pages: 534
      order: 1
      base_file: A1DD.txt
    DEBE:
      image_group_id: I5619
      title: ''
      total_pages: 626
      order: 2
      base_file: DEBE.txt
    3D35:
      image_group_id: I5620
      title: ''
      total_pages: 744
      order: 3
      base_file: 3D35.txt
    BBE9:
      image_group_id: I5621
      title: ''
      total_pages: 756
      order: 4
      base_file: BBE9.txt
    4B96:
      image_group_id: I5622
      title: ''
      total_pages: 580
      order: 5
      base_file: 4B96.txt
    4DB2:
      image_group_id: I5623
      title: ''
      total_pages: 696
      order: 6
      base_file: 4DB2.txt
    B5D9:
      image_group_id: I5624
      title: ''
      total_pages: 822
      order: 7
      base_file: B5D9.txt
    14B4:
      image_group_id: I5625
      title: ''
      total_pages: 632
      order: 8
      base_file: 14B4.txt
    B32B:
      image_group_id: I5626
      title: ''
      total_pages: 710
      order: 9
      base_file: B32B.txt
    9F85:
      image_group_id: I5627
      title: ''
      total_pages: 590
      order: 10
      base_file: 9F85.txt
    21B9:
      image_group_id: I5628
      title: ''
      total_pages: 632
      order: 11
      base_file: 21B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
