id: I4CEE4109
legacy_id: P005573
ocr_import_info:
  bdrc_scan_id: W29701
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T05:43:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:21:53.264588+00:00'
last_modified: 2022-09-02 22:33:41.425516
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29701
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29701
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཚེ་རྣམ།
  author: ཁྲོ་རུ་མཁན་པོ་ཚེ་རྣམ།
statistics:
  ocr_word_mean_confidence_index: 0.8673924463351366
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I5628:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5628
      total_pages: 632
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I5628.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9017879612950407
    legacy_id: v011
  I5618:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5618
      total_pages: 534
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5618.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8515379175713721
    legacy_id: v001
  I5624:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5624
      total_pages: 822
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I5624.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8775987006406392
    legacy_id: v007
  I5621:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5621
      total_pages: 756
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5621.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.861351725577874
    legacy_id: v004
  I5620:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5620
      total_pages: 744
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5620.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8491479668811925
    legacy_id: v003
  I5626:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5626
      total_pages: 710
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I5626.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.895758229359229
    legacy_id: v009
  I5625:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5625
      total_pages: 632
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I5625.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8734523341115041
    legacy_id: v008
  I5622:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5622
      total_pages: 580
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I5622.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8371702826544772
    legacy_id: v005
  I5627:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5627
      total_pages: 590
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I5627.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9142779157839616
    legacy_id: v010
  I5623:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5623
      total_pages: 696
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I5623.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8593910152931468
    legacy_id: v006
  I5619:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5619
      total_pages: 626
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5619.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8382029527406408
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
